export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const BOOKS_FETCHED = "BOOKS_FETCHED";
export const BOOK_CREATED = "BOOK_CREATED";
export const GET_SHORT_LINK_REQUEST = "GET_SHORT_LINK_REQUEST";
export const GET_SHORT_LINK_REQUEST_SUCCESS = "GET_SHORT_LINK_REQUEST_SUCCESS";
export const GET_SHORT_LINK_REQUEST_ERROR = "GET_SHORT_LINK_REQUEST_ERROR";
